// Licensed to Julian Hyde under one or more contributor license
// agreements.  See the NOTICE file distributed with this work
// for additional information regarding copyright ownership.
// Julian Hyde licenses this file to you under the Apache
// License, Version 2.0 (the "License"); you may not use this
// file except in compliance with the License.  You may obtain a
// copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied.  See the License for the specific
// language governing permissions and limitations under the
// License.

//! Datalog parser entry point. The actual grammar lives in
//! `grammar.lalrpop` and is generated at build time by `lalrpop`
//! (configured in `build.rs`).

use crate::datalog::ast::Program;
use crate::datalog::error::DatalogError;
use lalrpop_util::ParseError;
use std::fmt::Display;

// Generated by lalrpop from `src/datalog/grammar.lalrpop`. Allow lints
// that fire only inside the generated code so we don't have to patch
// it.
#[allow(clippy::all, dead_code, unused_imports)]
pub mod grammar {
    include!(concat!(env!("OUT_DIR"), "/datalog/grammar.rs"));
}

/// Parses a Datalog program from a string.
pub fn parse(input: &str) -> Result<Program, DatalogError> {
    grammar::ProgramParser::new()
        .parse(input)
        .map_err(|e| DatalogError::parse(format_parse_error(input, &e)))
}

/// Formats a LALRPOP `ParseError` in the JavaCC style used by
/// morel-java, so error messages are byte-for-byte identical across
/// implementations.
fn format_parse_error<T: Display, E: Display>(
    input: &str,
    err: &ParseError<usize, T, E>,
) -> String {
    match err {
        ParseError::InvalidToken { location } => {
            let (line, col) = line_col(input, *location);
            format!("Encountered \"\" at line {}, column {}.", line, col)
        }
        ParseError::UnrecognizedEof { location, expected } => {
            let (line, col) = line_col(input, *location);
            format_javacc("<EOF>", line, col, expected)
        }
        ParseError::UnrecognizedToken { token, expected } => {
            let (start, tok, _end) = token;
            let (line, col) = line_col(input, *start);
            format_javacc(&tok.to_string(), line, col, expected)
        }
        ParseError::ExtraToken { token } => {
            let (start, tok, _end) = token;
            let (line, col) = line_col(input, *start);
            format!(
                "Encountered extra token \"{}\" at line {}, column {}.",
                tok, line, col
            )
        }
        ParseError::User { error } => error.to_string(),
    }
}

/// Builds the canonical JavaCC-style "Encountered ... was expecting" message.
fn format_javacc(
    token: &str,
    line: usize,
    col: usize,
    expected: &[String],
) -> String {
    let mut out = format!(
        "Encountered \"{}\" at line {}, column {}.\nWas expecting one of:\n",
        token, line, col
    );
    for e in expected {
        out.push_str("    ");
        out.push_str(e);
        out.push_str(" ...\n");
    }
    out.push_str("    ");
    out
}

/// Returns the 1-based `(line, column)` of `offset` in `input`, where
/// `column` is measured in bytes from the start of the line. EOF at
/// the end of a single-line N-character input maps to column N, which
/// matches morel-java/JavaCC's reported position.
fn line_col(input: &str, offset: usize) -> (usize, usize) {
    let clamped = offset.min(input.len());
    let prefix = &input[..clamped];
    let line = prefix.bytes().filter(|b| *b == b'\n').count() + 1;
    let line_start = prefix.rfind('\n').map_or(0, |i| i + 1);
    (line, clamped - line_start)
}

/// Unescapes a quoted Souffle/Datalog string literal. Strips the
/// surrounding quotes and turns `\n`, `\r`, `\t`, `\\`, `\"` into the
/// corresponding characters. Used by the lalrpop grammar.
pub(crate) fn unescape(quoted: &str) -> String {
    let inner = &quoted[1..quoted.len() - 1];
    let mut out = String::with_capacity(inner.len());
    let mut chars = inner.chars();
    while let Some(c) = chars.next() {
        if c == '\\' {
            match chars.next() {
                Some('n') => out.push('\n'),
                Some('r') => out.push('\r'),
                Some('t') => out.push('\t'),
                Some('\\') => out.push('\\'),
                Some('"') => out.push('"'),
                Some(other) => {
                    out.push('\\');
                    out.push(other);
                }
                None => out.push('\\'),
            }
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::datalog::ast::{
        ArithOp, BodyAtom, CompOp, DatalogType, Statement, Term,
    };

    #[test]
    fn parse_empty_program() {
        let p = parse("").expect("parse");
        assert!(p.statements.is_empty());
    }

    #[test]
    fn parse_decl() {
        let p = parse(".decl edge(x:int, y:int)").expect("parse");
        assert_eq!(p.statements.len(), 1);
        match &p.statements[0] {
            Statement::Declaration(d) => {
                assert_eq!(d.name, "edge");
                assert_eq!(d.params.len(), 2);
                assert_eq!(d.params[0].name, "x");
                assert_eq!(d.params[0].ty, DatalogType::Int);
                assert_eq!(d.params[1].name, "y");
                assert_eq!(d.params[1].ty, DatalogType::Int);
            }
            _ => panic!("expected Declaration"),
        }
    }

    #[test]
    fn parse_input_with_and_without_filename() {
        let p = parse(".input edge \"data.csv\" .input node").expect("parse");
        assert_eq!(p.statements.len(), 2);
        match &p.statements[0] {
            Statement::Input(i) => {
                assert_eq!(i.relation, "edge");
                assert_eq!(i.file_name.as_deref(), Some("data.csv"));
            }
            _ => panic!("expected Input"),
        }
        match &p.statements[1] {
            Statement::Input(i) => {
                assert_eq!(i.relation, "node");
                assert!(i.file_name.is_none());
                assert_eq!(i.effective_file_name(), "node.csv");
            }
            _ => panic!("expected Input"),
        }
    }

    #[test]
    fn parse_output() {
        let p = parse(".output ancestor").expect("parse");
        match &p.statements[0] {
            Statement::Output(o) => assert_eq!(o.relation, "ancestor"),
            _ => panic!("expected Output"),
        }
    }

    #[test]
    fn parse_fact_with_int_and_string() {
        let p = parse("parent(\"earendil\", 42).").expect("parse");
        match &p.statements[0] {
            Statement::Fact(f) => {
                assert_eq!(f.atom.name, "parent");
                assert_eq!(f.atom.terms.len(), 2);
                assert_eq!(
                    f.atom.terms[0],
                    Term::StringConst("earendil".into())
                );
                assert_eq!(f.atom.terms[1], Term::IntConst(42));
            }
            _ => panic!("expected Fact"),
        }
    }

    #[test]
    fn parse_rule_with_negation_and_comparison() {
        let src = "ancestor(X, Z) :- parent(X, Y), !sibling(Y, Z), Y < Z.";
        let p = parse(src).expect("parse");
        match &p.statements[0] {
            Statement::Rule(r) => {
                assert_eq!(r.head.name, "ancestor");
                assert_eq!(r.body.len(), 3);
                match &r.body[1] {
                    BodyAtom::Atom { negated, atom } => {
                        assert!(*negated);
                        assert_eq!(atom.name, "sibling");
                    }
                    _ => panic!("expected negated atom"),
                }
                match &r.body[2] {
                    BodyAtom::Comparison { op, .. } => {
                        assert_eq!(*op, CompOp::Lt);
                    }
                    _ => panic!("expected comparison"),
                }
            }
            _ => panic!("expected Rule"),
        }
    }

    #[test]
    fn parse_arithmetic_in_term() {
        // 1 + 2 * 3 → Plus(1, Times(2, 3))
        let p = parse("succ(N + 1).").expect("parse");
        match &p.statements[0] {
            Statement::Fact(f) => match &f.atom.terms[0] {
                Term::Arith { left, op, right } => {
                    assert_eq!(**left, Term::Variable("N".into()));
                    assert_eq!(*op, ArithOp::Plus);
                    assert_eq!(**right, Term::IntConst(1));
                }
                _ => panic!("expected Arith"),
            },
            _ => panic!("expected Fact"),
        }

        // Precedence: parse "K(1 + 2 * 3)" as 1 + (2 * 3)
        let p = parse("k(1 + 2 * 3).").expect("parse");
        if let Statement::Fact(f) = &p.statements[0]
            && let Term::Arith {
                op: ArithOp::Plus,
                right,
                ..
            } = &f.atom.terms[0]
        {
            match right.as_ref() {
                Term::Arith {
                    op: ArithOp::Times, ..
                } => {}
                _ => panic!("expected nested Times under Plus"),
            }
        } else {
            panic!("unexpected shape");
        }
    }

    #[test]
    fn parse_string_escapes() {
        let p = parse("msg(\"a\\nb\\\"c\").").expect("parse");
        if let Statement::Fact(f) = &p.statements[0]
            && let Term::StringConst(s) = &f.atom.terms[0]
        {
            assert_eq!(s, "a\nb\"c");
        } else {
            panic!("unexpected shape");
        }
    }

    #[test]
    fn parse_skips_comments() {
        let src = "// line comment\n\
                   # hash comment\n\
                   /* block\ncomment */\n\
                   .decl r(x:int)";
        let p = parse(src).expect("parse");
        assert_eq!(p.statements.len(), 1);
    }

    #[test]
    fn parse_error_returns_datalog_error() {
        let err = parse(".decl edge(x:int").unwrap_err();
        match err {
            DatalogError::Parse(_) => {}
            _ => panic!("expected Parse error"),
        }
    }
}
